-   id: format-python-and-sql-in-markdown-files
    name: format python and sql snippets in markdown files
    description: formats python and sql snippets (with black and sqlfluff).
    entry: format-sql-python-in-md
    language: python
    stages: [commit]
