-   id: format-markdown-code-snippets
    name: format python and sql snippets in markdown files
    description: formats python and sql snippets (with black and sqlfluff).
    entry: format-markdown-code-snippets
    language: python
    stages: [commit]
    types: [markdown]
